### ISSUE TITLE
Failed to run some hash routing strategies

### ISSUE THREAD

**Issue by ashimdey052** [icarus-sim/icarus#20]
Hello Sir,
I am facing some problems with running `'HR_EDGE_CACHE'`, '`HR_ON_PATH'` and `'HR_CLUSTER'` strategies which are not shown in the examples. When I try to run any of these strategies, the error shows :
`ERROR|orchestration] FAILURE | Experiment failed: list index out of range`

I have assigned 'MULTICAST' for `'HR_EDGE_CACHE'`, '`HR_ON_PATH'` and `'HR_CLUSTER'`.

Here is my errors, config and hashrouting files. Kindly have a look.
[Errors.txt](https://github.com/icarus-sim/icarus/files/5719858/Errors.txt)
[config.txt](https://github.com/icarus-sim/icarus/files/5719857/config.txt)
[hashrouting.txt](https://github.com/icarus-sim/icarus/files/5719856/hashrouting.txt)

Am I missing something? It will be great if you help me out, sir!

**Comment by ashimdey052** [comment]
Hello Sir,
Merry Christmas and Happy new year! I have able to solve the problem during running `HR_EDGE_CACHE', 'HR_ON_PATH'`. But when I try to run `'HR_CLUSTER'` on real topologies like 'GEANT', 'WIDE','GARR' , an error shows `ValueError: There are nodes not labelled with cluster information`. Should I run this on different topologies?
How can I resolve it, sir?

**Comment by lorenzosaino** [comment]
Hi Ashim, glad to hear you were able to solve your first problem.

The reason for this issue is that, when using `HR_CLUSTER` as a strategy, you also need an algorithm that assigns cache nodes to clusters. See sec. 4.C of [this paper](https://lorenzosaino.github.io/publications/hashrouting-tnsm.pdf). That error message emerged because the `HR_CLUSTER` strategy expects the topology to include data telling which cache node belongs to each cluster, but it didn't.

To do this, you need to use a cache placement algorithm that also assigns cache nodes to clusters. You can create one of your own or use can use the `CLUSTERED_HASHROUTING` cache placement algorithm implemented here: https://github.com/icarus-sim/icarus/blob/1f80c39b503b983771810e97e43d89959a4a2782/icarus/scenarios/cacheplacement.py#L294-L351

The design of that algorithm is described in Sec. 7.E of [this paper](https://lorenzosaino.github.io/publications/hashrouting-tnsm.pdf).

You can use that cache placement algorithm with every topology.

Hope this helps, please let me know if you have any further issue.

**Comment by ashimdey052** [comment]
Thank you for replying, Sir! It works! 
Actually, I want to compare and plot all available hash routing strategies in a single experiment. So, for  `HR_CLUSTER`, I should declare `default['cache_placement']['name'] = 'CLUSTERED_HASHROUTING'` and for other hash routing strategies `default['cache_placement']['name'] = 'UNIFORM'` . How can I handle this conflict in a single experiment?
Sorry for my endless question :(

**Comment by lorenzosaino** [comment]
You can do it. There are two ways to do it, as far as I can tell.

1. You can use the `CLUSTERED_HASHROUTING` cache placement everywhere, also on non-hashrouting strategies. It should work fine. If you set `default['cache_placement']['policy'] = 'node_const'`, that effectively has the same behavior of the `UNIFORM` cache placement policy when used with non-hashrouting strategies.
2. The configuration file is interpreted as standard Python code, so you can use any Python statements. You could add a conditional to use `CLUSTERED_HASHROUTING` for hashrouting policies and `UNIFORM` for others. That would look like this (you will need to adapt it for your specific config file):

```python
if experiment['strategy']['name'] == "HR_CLUSTER":
    experiment['cache_placement']['name'] = 'CLUSTERED_HASHROUTING'
else:
   experiment['cache_placement']['name'] = 'UNIFORM'
```

**Comment by ashimdey052** [comment]
Sir!
Thank you for answering with great patience. I am still uncovering **_Icarus_** and trying to make the best use of it!

**Comment by lorenzosaino** [comment]
I am closing this issue for now. If you have any further issues, please feel free to reopen it.

**Comment by ashimdey052** [comment]
Hello Sir!
How can I find these two things from icarus:
1. Popularity of content `p` (out of 1.0) at any time `t`
2. Available free Cache size `c` (out of 1.0) of a Cache Node `n` at any time `t`

**Comment by lorenzosaino** [comment]
Hi Ashim,

1. It depends on the workload you are using. If you are using the stationary workload, then the popularity of each item is constant over the simulation. If you are using a trace driven workload, then you need to measure it from the trace. If you need to compute the popularity online, i.e., you want your strategy to learn the popularity while the simulation is being executed, you will need to implement code to do that. There is no function to get that information at the moment.
2. There's no method to get the current free among of cache, typically because in simulations, cache is expected to be always filled at steady-state. If you need to compute this online and make it accessible to your strategy, the way I would go about would be to add a method to the NetworkView class that returns that. I think it shouldn't be too difficult to implement.

**Comment by ashimdey052** [comment]
1. Yes, Sir. I am using `stationary workload` (means content popularity is Zipf-distributed), then maybe the popularity of each item is constant over the simulation. But how I can find that `popularity value` (maybe constant overtime) for some content `i` at any time `t` during `j` th request? For that, if no function is available, can you provide any guidance for implementation?

2. Sir, Can you be more specific about this implementation?
