### ISSUE TITLE
Error after completion of simulation

### ISSUE THREAD

**Issue by anantatapase** [icarus-sim/icarus#4]
After the completion of simulation in ubuntu there was error as 
IOError: [Errno 13] Permission denied: 'results.pickle'
any help why this error occurs?

**Comment by lorenzosaino** [comment]
I can't tell exactly without seeing the actual command line parameters you used. However, with all probability, this error occurred because the results file that you specified in the `--results` arguments either refers to a directory that does not exist or your user does not have write permission on that directory.
